In [1]:
# read each line of the file 
# Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
import pandas as pd

# create a dataframe 
df_final = []
with open('serverh7.txt') as file_in:
    for line in file_in:
        list_col = line.split()
        if list_col[0] == '[SUM]':
            # new_df = { 'Transfer': list_col[4], 'Bandwidth': list_col[6], 'Jitter': list_col[8], 'Lost': list_col[10], 'Total': list_col[9], 'Datagrams': list_col[10] }
            # print(list_col)
            # if list_col[0][-1] == '-':
            if len(list_col) == 13:
                new_df =  [float(list_col[4]), float(list_col[6]), float(list_col[8]), float(list_col[10][:-1]), float(list_col[11]), float(list_col[12][1:-2]) ]
            elif len(list_col) == 12:
                new_df = [float(list_col[3]), float(list_col[5]), float(list_col[7]),  float(list_col[9][:-1]), float(list_col[10]), float(list_col[11][1:-2])]
            else:
                continue
            df_final.append(new_df)

In [2]:
import numpy as np
df_final = np.array(df_final)

In [3]:
# convert numpy 2D to dataframe
pd.DataFrame(df_final, columns=['Transfer', 'Bandwidth', 'Jitter', 'Lost', 'Total', 'Datagrams'])

      Transfer  Bandwidth  Jitter    Lost   Total  Datagrams
0       655.00       5.36   0.020    10.0   466.0        2.1
1         1.02       8.56   0.010    24.0   752.0        3.2
2         1.02       8.55   0.135    19.0   746.0        2.5
3         1.01       8.43   0.011    36.0   753.0        4.8
4         1.03       8.67   1.183    26.0   763.0        3.4
...        ...        ...     ...     ...     ...        ...
1475      4.31      35.30   6.728   729.0   732.0      100.0
1476      1.14       9.55   0.715   618.0  1430.0       43.0
1477     14.40     118.00  68.988  5746.0  5756.0      100.0
1478      1.13       9.49   0.677   621.0  1428.0       43.0
1479     11.50      94.10  90.606   481.0   489.0       98.0

[1480 rows x 6 columns]